version: "v2.31.0-desktop.2"
services:
  project-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: foundation
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
  project-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: foundation-prod
    ports:
      - "8000:80"
